### PR TITLE
Bump cilium app version to 0.10.0

### PR DESCRIPTION
**Pull request by erkanerol**
Towards https://github.com/giantswarm/giantswarm/issues/27728

Conformance tests have failed with this error

```
[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
```

As far as I understand from [this](https://github.com/giantswarm/roadmap/issues/1346) issue, it is because of the cilium version. CAPZ passed the conformance tests and it has the newer version. This change is supposed to fix the conformance tests.

I applied the toleration changes in CAPVCD to this manifest too. See https://github.com/giantswarm/cluster-cloud-director/commit/bf00c740f80e2b910a182cd1ea0dfe0c0353cc35

<details>
  <summary>How to run CI</summary>

Comment on this PR with:

```
/run cluster-test-suites
```
</details>

### CODE REVIEW

**Comment by erkanerol** [comment]
This already passed normal tests but failed because of a bug in upgrade tests. See https://github.com/giantswarm/cluster-test-suites/pull/61

Can be merged. @giantswarm/team-rocket Please review.

**Review by glitchcrab — APPROVED** [review]
looks reasonable to me

**Pull request merged**
