### PR TITLE
test renovate cloud provider

### PR DESCRIPTION
**Pull request by vxav**
https://github.com/giantswarm/cloud-provider-vsphere-app/pull/181

### CODE REVIEW

**Comment by vxav** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Comment by vxav** [comment]
E2E tests already succeeded, just testing https://gigantic.slack.com/archives/C01BYMF6RN0/p1728887626006229

/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Comment by vxav** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Review by anvddriesch — APPROVED** [review]

**Comment by vxav** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Comment by vxav** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/standard

**Pull request closed without merging**
