### PR TITLE
chart cleanup

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/31983

Instead of reviewing the PR from the changed files tab, It's probably easier to review the individual commits below because i've grouped the changes together logically.

### CODE REVIEW

**Comment by glitchcrab** [comment]
I think this is good to review - I'm going to try running the e2e tests but I don't think they're necessary as the diff check shows no changes have been introduced.

**Review by anvddriesch — APPROVED** [review]

**Review by vxav — APPROVED** [review]
LGTMIIWFY

It looks like you know what you're doing _(I don't)_

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/on-capa

**Comment by glitchcrab** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capv/on-capa

**Comment by glitchcrab** [comment]
ok, i've had enough of this PR, going to merge it now

**Pull request merged**
